window.seraph_wd||(window.seraph_wd={});
(function(){seraph_wd.PluginAdmin={AdvertProductsContentInit:function(a,c,b,d,g,f){function e(k,B){var m="";if(Array.isArray(k)&&k.length){m+=seraph_wd.Ui.TagOpen("tr");for(var p=0;p<k.length;p++){var n=k[p];0<p&&0==p%g&&(m+=seraph_wd.Ui.TagClose("tr")+seraph_wd.Ui.TagOpen("tr"));var w=seraph_wd.Ui,C=w.Tag,x=seraph_wd.Ui,D=x.Tag,y=B,q="";var l=n.images;var t=y;if(Array.isArray(l)){for(var u=-1,z=2147483647,v=-1,A=2147483647,r=0;r<l.length;r++){var h=l[r];if(t==h.width){u=r;break}t<h.width?(h=h.width-
t,h<z&&(u=r,z=h)):(h=t-h.width,h<A&&(v=r,A=h))}l=-1!=u?l[u].url:-1!=v?l[v].url:null}else l=null;l&&(q+=seraph_wd.Ui.Tag("td",seraph_wd.Ui.Link(seraph_wd.Ui.Tag("img",null,{"class":"ctlSpaceAfter",width:y,src:l},!0),n.urlInfo,!0),{style:{width:"1px"}}));q+=seraph_wd.Ui.TagOpen("td");q+=seraph_wd.Ui.Tag("h3",n.title,{"class":"ctlSpaceVAfter",style:{"margin-top":0}});q+=seraph_wd.Ui.Tag("div",n.descr);n.urlInfo&&(q+=seraph_wd.Ui.Button(d,!0,null,"ctlSpaceVBefore","button",{onclick:"window.open( '"+n.urlInfo+
"', '_blank' )"}));q+=seraph_wd.Ui.TagClose("td");n=seraph_wd.Ui.Tag("table",seraph_wd.Ui.Tag("tbody",seraph_wd.Ui.Tag("row",q)));m+=C.call(w,"td",D.call(x,"div",n,{style:{margin:"1em 1em 2em 1em"}}),{"class":"cx-lg-6 cx-xs-12",style:{"vertical-align":"top"}})}for(;p%g;p++)m+=seraph_wd.Ui.Tag("td",null,{"class":"cx-lg-6 cx-xs-12"});m+=seraph_wd.Ui.TagClose("tr");m=seraph_wd.Ui.Tag("table",seraph_wd.Ui.Tag("tbody",m))}jQuery(a).html(m)}jQuery.ajax({url:seraph_wd.Net.UpdateQueryArgs(c+"/v1/advert_products",
{slug:"woo-discount",locale:b}),type:"GET",dataType:"json"}).then(function(k){e(k,f)},function(k){e(null,0)})},SwitchTo:function(a,c,b){function d(e,k){g.hide();f.prop("disabled",!1);e&&window.open(b,"_blank").focus()}a=jQuery(".seraph_wd_switchto");var g=a.find(".seraph_wd_spinner"),f=a.find('input[type="button"]:not(.cancel)');g.show();f.prop("disabled",!0);jQuery.ajax({url:c,type:"post"}).then(function(e){d(!0)},function(e){d(!1,"OK"===e.statusText?"PHP error: "+e.responseText:"Backend error: "+
e.status+" "+e.statusText)})},RateItCont_Set:function(a,c,b){var d=jQuery("#"+a),g=d.find(".actions"),f=d.find(".seraph_wd_spinner");g.hide();f.show();jQuery.ajax({url:b+"="+(c?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(e){d.hide()},function(e){g.show();f.hide()})},RateIt_Set:function(a,c){jQuery("#seraph_wd_RateIt_Message .actions").hide();jQuery("#seraph_wd_RateIt_Message .seraph_wd_spinner").show();jQuery.ajax({url:c+"="+(a?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(b){seraph_wd.Ui.BannerMsgClose(jQuery("#seraph_wd_RateIt_Message"))},
function(b){jQuery("#seraph_wd_RateIt_Message .actions").show();jQuery("#seraph_wd_RateIt_Message .spinner").hide()})},ChangeVersion_Confirm:function(a){jQuery("#seraph_wd_ChangeVersion_Msg .actions").hide();jQuery("#seraph_wd_ChangeVersion_Msg .seraph_wd_spinner").show();jQuery.ajax({url:a+"=changeVersionConfirm",type:"post"}).then(function(c){seraph_wd.Ui.BannerMsgClose(jQuery("#seraph_wd_ChangeVersion_Msg"))},function(c){jQuery("#seraph_wd_ChangeVersion_Msg .actions").show();jQuery("#seraph_wd_ChangeVersion_Msg .spinner").hide()})},
SettImport:function(a,c,b){function d(){f.prop("disabled",!1);g.hide()}if(b){a=jQuery(a.parentNode);var g=a.find(".seraph_wd_spinner"),f=a.find("input.button");f.prop("disabled",!0);g.show();a=new FileReader;a.onabort=function(e){d()};a.onerror=function(e){d()};a.onload=function(e){jQuery.ajax({url:c+"=settImport",type:"post",contentType:"application/json",data:e.target.result}).then(function(){location.reload()},function(k){d()})};a.readAsText(b)}},SettExport:function(a,c){function b(f){f&&window.saveAs(new Blob([f],
{type:"text/json"}),"seraphinite-discount-for-woocommerce-settings.json");g.prop("disabled",!1);d.hide()}a=jQuery(a.parentNode);var d=a.find(".seraph_wd_spinner"),g=a.find("input.button");g.prop("disabled",!0);d.show();jQuery.ajax({url:c+"=settExport",type:"post"}).then(function(f){seraph_wd.Ui.ScriptLoad(document,"https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js","file-saver").then(function(){b(f)},function(e){b()})},function(f){b()})},OnSettWizNext:function(a,c){var b=jQuery(a).closest("form");
a=jQuery(a.parentNode);var d=b.find(".wizPages");b=d.find(">.active").first();b.get(0)?(c=c?b.next():b.prev(),c.get(0)&&(b.removeClass("active"),b=c)):b=d.children().first();b.addClass("active");c=!!b.next().get(0);b=!!b.prev().get(0);a.find("input.wizNext").prop("disabled",!c);a.find("input.wizPrev").prop("disabled",!b);c?a.find("input.wizFinish").hide():a.find("input.wizFinish").show()}}})();
